## Numpy

* Recall list and it's wonderful properties. There is a downfall in list. It can be so 1-D Dimension. It allows multiple datatypes as it's values which is an advantage. Let's see why do we use Numpy.

* Numpy can be 2-Dimensional or more. Numpy has a datatype known as arrays. 

* Numpy is a library package. From numpy, we use certain modules, which can be a book or page from numpy library. 

* It can hold more than one value, but it should always be elements of same datatype in ordered format.

* Numpy is used to work wih numerical data in python.
* Makes numerical computation easier, faster and by using this library, you will reduce the lenght of the code, so less memoory is consumed during execution.

### Vector and Matrix

* Vector is a 1-D numpy array.
* Matrix is an arrangement of numbers into rows and columns,it can have minimum of a row and a column.
* Matrix is always represented rows * cloumns. 

In [1]:
# import numpy libraries

import numpy as np # np is referred as alias which is used widely to make sure the code is pretty and readable.

# sample list
sample_list = [2,4,6,8,10]
print(sample_list, '\n \n', type(sample_list))

[2, 4, 6, 8, 10] 
 
 <class 'list'>


In [2]:
numpy_array1 = np.array(sample_list)
print(type(numpy_array1))

<class 'numpy.ndarray'>


In [3]:
numpy_array1

array([ 2,  4,  6,  8, 10])

In [4]:
#Create a NumPy array of the first five even numbers.

import numpy as np
nump_arr = np.arange(0,10,2)
print(nump_arr)

[0 2 4 6 8]


In [5]:
numpy_array2 = np.array([[4,5,6],[456,45,467],[1234,5647,4897],[40,50,80]])

print(numpy_array2) 
# 4 rows and 3 colums

[[   4    5    6]
 [ 456   45  467]
 [1234 5647 4897]
 [  40   50   80]]


In [6]:
type(numpy_array2) #find the type of the variable numpy_array2

numpy.ndarray

In [7]:
numpy_array2.size #find the size or how many values present in the numpy array

12

In [8]:
numpy_array2.dtype #find the datype of the varaiable name numpy_array2

dtype('int32')

In [9]:
numpy_array2.shape #shape of the numpy array

(4, 3)

In [10]:
numpy_array2.ndim # dimension of the numpy array

2

In [12]:
#some more basic function in numpy array
#arange() - collection of continious integers or floats

numpy_array3 = np.arange(10)
numpy_array3

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
#np.zeros - numpy array with values with all 0

numpy_array4 = np.zeros(10)
numpy_array4

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [14]:
#np.ones - numpy array with values with all 1

numpy_array5 = np.ones(5)
numpy_array5

array([1., 1., 1., 1., 1.])

In [15]:
#np.linspace - generates values which are equally spaced from each other

numpy_array6 = np.linspace(start = 5, stop = 10, num = 5)
numpy_array6 # values between 5.0 and 10.0 are spaced with equal width of 5 counts

array([ 5.  ,  6.25,  7.5 ,  8.75, 10.  ])

In [23]:
#append() - add a new value to the existing array

print(np.append(numpy_array6, 25)) #with this, a new value 25, has been added to numpy_array6

[ 5.    6.25  7.5   8.75 10.   25.  ]


##### A simple note :: 

### In list, print will seperate the value with a seperator referred as comma or ','.
### In numpy array, print will display the value with whitespace which is in and itself is a seperator.

In [24]:
#delete() - remove an element from the numpy array

print(np.delete(numpy_array6,2)) #2 will be the index location, which starts at 0

[ 5.    6.25  8.75 10.  ]


In [25]:
#sort() - sort an numpy array with ascending order.
numpy_array7= np.array([7,3,8,1,9,4,6,5])
print(np.sort(numpy_array7))

[1 3 4 5 6 7 8 9]


In [28]:
#sorting in descending order

numpy_array7[::-1].sort()
numpy_array7

array([9, 8, 7, 6, 5, 4, 3, 1])

In [29]:
#reshape() - reshape the array, but the new array should have same number of values as previous unreshaped array

numpy_array8 = np.arange(24)
numpy_array8

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [30]:
# we use reshape but, we should consider multiple of 24, ie 4*6, 6*4, 12*2,2*12, 3*8,8*3

np.reshape(numpy_array8,(3,8)) #3 rows, 8 columns

array([[ 0,  1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20, 21, 22, 23]])

In [44]:
# indexing

#positive indexing :: rows - from left to right, starts with 0, column left to right starts with 0

num_arr = np.array([[2,4,6],[8,10,12],[5,5,5],[36,19,25]])
num_arr

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [ 5,  5,  5],
       [36, 19, 25]])

In [41]:
num_arr[0] #since numpy is rows and columns and the first row is indexed as 0

array([2, 4, 6])

In [42]:
num_arr[0,0]#indexed row 0th position and column 0th position

2

In [43]:

num_arr[0][0]

2

In [47]:
#positive slicing

num_arr[0:3, 0:2] #0:3 - sliced from row 0th position to row 3rd position and 0:2 - sliced from 0th column and 2nd column position

array([[ 2,  4],
       [ 8, 10],
       [ 5,  5]])

In [48]:
#negative indexing :: rows - from right to left, starts with -1, column right to left starts with -1

num_arr[-1]

array([36, 19, 25])

In [49]:
num_arr[-1,-1]

25

In [52]:
L = np.arange(25)

In [53]:
l = np.reshape(L, (5,5))
l

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19],
       [20, 21, 22, 23, 24]])

In [57]:
l[:1,::4]

array([[0, 4]])

## Pandas

* A simple, robust data manipulation tool.
* Used extensively for data analysis, understanding the data and handling data for tasks like merging, joinging, aggregation and transformation.
* Pandas helps you to analyse what your data means which has been collected through various interval of time. An important task is to understand the data, analyse the data before we end up used in modelling a machine to give us an estimation.
* Data in tabular format helps breakdown on further analysis which saves time, resorces and cost.Pandas provides insightful information.

### import pandas library as pd which is an alias

import pandas as pd

### to read a csv file, you can use some thing like 
pd.read_csv("file path/location.")

### to read an excel file, you can use this
pd.read_excel('filepath/location', sheet_name = "If you have multiple sheets in excel, this will helps pandas to load correct dataset.")

### Pandas DataStructure

    1. series
    2. dataframe
    

### pandas - series

##### An 1-Dimensional array with homogenous data. It should be same datatype.
##### creating a pandas series.

##### dataset_series = pd.Series(data, index, dtype, copy)

    1. data: data takes various forms like ndarray, list, constants
    2. index: Index values must be unique and hashable, same length as data. Default np.arrange(n) if no
    3. index is passed.
    4. dtype: dtype is for data type.
    5. copy: Copy data. Default False


In [58]:
import pandas as pd

data = np.array(['a','b','c','d'])
s = pd.Series(data, index = [100,101,102,103])
s

100    a
101    b
102    c
103    d
dtype: object

### pandas - DataFrame

##### An 2-Dimensional array with homogenous data. It should be same datatype.
##### creating a pandas dataframe.

##### dataset_dataframe = pd.DataFrame(data, index, columns, dtype, copy)

    1. data: data takes various forms like ndarray, series, map, lists, dict, constants and also another DataFrame.
    2. index: For the row labels, the Index to be used for the resulting frame is Optional Default np.arange(n) if no index            is passed
    3. columns:  For column labels, the optional default syntax is - np.arange(n). This is only true if no index is passed.
    4. dtype: Data type of each column.
    5. copy: This command (or whatever it is) is used for copying of data, if the default is False.


In [60]:
import pandas as pd

data_df = [1,2,3,4,5]
df = pd.DataFrame(data)
print(df)


   0
0  a
1  b
2  c
3  d


In [62]:
data_df2 =  [['Alex',10],['Bob',12],['Clarke',13]]
df2 = pd.DataFrame(data_df2,columns=['Name','Age'])
print(df2)

#By specifying columns name, we have a better and easily analysable table.

     Name  Age
0    Alex   10
1     Bob   12
2  Clarke   13


#### Method and attributes of any dataframe

    1. shape - rows and columns of your working dataframe
    2. head() - shows top 5 rows and all the columns in the dataframe. 
        2A. head(10) - shows the top 10 rows and all the columns in the dataframe
    3. tail() - show the last 5 rows and all the columns in the dataframe
        3A. tail(25) - shows the last or bottom 25 rows and all columns in the dataframe.
    4. dtypes - shows all the datatype of the column in the dataframe.
    5. info() - the most important method, which will help us to find how many values we have and how many null values the            dataframe have.

In [63]:
dataset = pd.read_csv("https://raw.githubusercontent.com/dphi-official/Datasets/master/Standard_Metropolitan_Areas_Data-data.csv")

In [64]:
dataset.shape

(99, 10)

In [65]:
dataset.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 99 entries, 0 to 98
Data columns (total 10 columns):
land_area         99 non-null int64
percent_city      99 non-null float64
percent_senior    99 non-null float64
physicians        99 non-null int64
hospital_beds     99 non-null int64
graduates         99 non-null float64
work_force        99 non-null float64
income            99 non-null int64
region            99 non-null int64
crime_rate        99 non-null float64
dtypes: float64(5), int64(5)
memory usage: 7.9 KB


### Indexing, Selecting and Assigning

#### Indexing - Selecting particular rows and columns in the dataframe.
    
    1. loc - selecting data based on the labels
    2. iloc - selecting data based on the numerical position.
    

In [69]:
#iloc

print(dataset.iloc[0])

print(dataset.head(5))

land_area          1384.00
percent_city         78.10
percent_senior       12.30
physicians        25627.00
hospital_beds     69678.00
graduates            50.10
work_force         4083.90
income            72100.00
region                1.00
crime_rate           75.55
Name: 0, dtype: float64
   land_area  percent_city  percent_senior  physicians  hospital_beds  \
0       1384          78.1            12.3       25627          69678   
1       3719          43.9             9.4       13326          43292   
2       3553          37.4            10.7        9724          33731   
3       3916          29.9             8.8        6402          24167   
4       2480          31.5            10.5        8502          16751   

   graduates  work_force  income  region  crime_rate  
0       50.1      4083.9   72100       1       75.55  
1       53.9      3305.9   54542       2       56.03  
2       50.6      2066.3   33216       1       41.32  
3       52.2      1966.7   32906       2       

In [70]:
print(dataset.iloc[0,0])

1384


In [71]:
print(dataset.iloc[0:5, 0: 8]) #rows 0th position to 5th position and columns 0th position to 8th position

   land_area  percent_city  percent_senior  physicians  hospital_beds  \
0       1384          78.1            12.3       25627          69678   
1       3719          43.9             9.4       13326          43292   
2       3553          37.4            10.7        9724          33731   
3       3916          29.9             8.8        6402          24167   
4       2480          31.5            10.5        8502          16751   

   graduates  work_force  income  
0       50.1      4083.9   72100  
1       53.9      3305.9   54542  
2       50.6      2066.3   33216  
3       52.2      1966.7   32906  
4       66.1      1514.5   26573  


In [73]:
print(dataset.loc[0,['land_area', 'percent_city']])

land_area       1384.0
percent_city      78.1
Name: 0, dtype: float64


In [74]:
dataset.land_area #attributes dot based selection

0     1384
1     3719
2     3553
3     3916
4     2480
      ... 
94    1511
95    1543
96    1011
97     813
98     654
Name: land_area, Length: 99, dtype: int64

In [77]:
dataset[['graduates','work_force']] #dictionary based selection

graduates  work_force
0        50.1      4083.9
1        53.9      3305.9
2        50.6      2066.3
3        52.2      1966.7
4        66.1      1514.5
..        ...         ...
94       50.4       127.2
95       30.3        80.6
96       70.7        93.2
97       58.0        97.0
98       55.1        66.9

[99 rows x 2 columns]

In [79]:
dataset[dataset.graduates >= 70.0] # conditional selection

land_area  percent_city  percent_senior  physicians  hospital_beds  \
13        782          28.4             7.8        3119           8656   
81       2710          63.7             6.2         357           1277   
84       2737          45.0            10.5         602           1462   
96       1011          37.8            10.5         264            964   

    graduates  work_force  income  region  crime_rate  
13       70.5       915.2   12591       4       63.20  
81       72.8       110.9    1639       4       63.10  
84       71.3       131.4    1980       4       63.44  
96       70.7        93.2    1337       3       60.16

In [83]:
#summary functions

dataset.describe()

#count -total no of values used, #mean, std are statistical concept. #min and max are the values, #25,50,75 are the quartiles
#sometimes, 50% or 2nd quartile is referred as Median.

land_area  percent_city  percent_senior    physicians  \
count     99.000000     99.000000       99.000000     99.000000   
mean    2615.727273     42.518182        9.781818   1828.333333   
std     3045.826210     17.348277        2.524547   3192.199763   
min       47.000000     13.400000        3.900000    140.000000   
25%     1408.000000     30.100000        8.350000    459.000000   
50%     1951.000000     39.500000        9.700000    774.000000   
75%     2890.500000     52.600000       10.750000   1911.500000   
max    27293.000000    100.000000       21.800000  25627.000000   

       hospital_beds  graduates   work_force        income     region  \
count      99.000000  99.000000    99.000000     99.000000  99.000000   
mean     6345.868687  54.463636   449.366667   6762.505051   2.494949   
std      9136.202716   7.773286   610.990885  10393.349660   1.013921   
min       481.000000  30.300000    66.900000    769.000000   1.000000   
25%      2390.000000  50.250000   150.300000   2003.000000   2.000000   
50%      3472.000000  54.000000   257.200000   3510.000000   3.000000   
75%      6386.500000  58.300000   436.500000   6283.500000   3.000000   
max     69678.000000  72.800000  4083.900000  72100.000000   4.000000   

       crime_rate  
count   99.000000  
mean    55.643030  
std     13.470943  
min     23.320000  
25%     46.115000  
50%     56.060000  
75%     63.860000  
max     85.620000

In [88]:
dataset.describe().loc[['count','mean','std','50%']] #Cherry pick only few attributes for easier understanding.

land_area  percent_city  percent_senior   physicians  hospital_beds  \
count    99.000000     99.000000       99.000000    99.000000      99.000000   
mean   2615.727273     42.518182        9.781818  1828.333333    6345.868687   
std    3045.826210     17.348277        2.524547  3192.199763    9136.202716   
50%    1951.000000     39.500000        9.700000   774.000000    3472.000000   

       graduates  work_force        income     region  crime_rate  
count  99.000000   99.000000     99.000000  99.000000   99.000000  
mean   54.463636  449.366667   6762.505051   2.494949   55.643030  
std     7.773286  610.990885  10393.349660   1.013921   13.470943  
50%    54.000000  257.200000   3510.000000   3.000000   56.060000

In [90]:
dataset[['land_area', 'percent_city']].describe().loc[['count','mean','std','50%']] 
#cherry pick few features and few attributes for easier analysis

land_area  percent_city
count    99.000000     99.000000
mean   2615.727273     42.518182
std    3045.826210     17.348277
50%    1951.000000     39.500000

land_area  percent_city  percent_senior    physicians  \
count     99.000000     99.000000       99.000000     99.000000   
mean    2615.727273     42.518182        9.781818   1828.333333   
std     3045.826210     17.348277        2.524547   3192.199763   
min       47.000000     13.400000        3.900000    140.000000   
25%     1408.000000     30.100000        8.350000    459.000000   
50%     1951.000000     39.500000        9.700000    774.000000   
75%     2890.500000     52.600000       10.750000   1911.500000   
max    27293.000000    100.000000       21.800000  25627.000000   

       hospital_beds  graduates   work_force        income     region  \
count      99.000000  99.000000    99.000000     99.000000  99.000000   
mean     6345.868687  54.463636   449.366667   6762.505051   2.494949   
std      9136.202716   7.773286   610.990885  10393.349660   1.013921   
min       481.000000  30.300000    66.900000    769.000000   1.000000   
25%      2390.000000  50.250000   150.300000   2003.000000   2.000000   
50%      3472.000000  54.000000   257.200000   3510.000000   3.000000   
75%      6386.500000  58.300000   436.500000   6283.500000   3.000000   
max     69678.000000  72.800000  4083.900000  72100.000000   4.000000   

       crime_rate  
count   99.000000  
mean    55.643030  
std     13.470943  
min     23.320000  
25%     46.115000  
50%     56.060000  
75%     63.860000  
max     85.620000

In [94]:
# aggregation

print(dataset.mean()) #just mean of all the features and their values

print("\n \n",dataset.median())

land_area         2615.727273
percent_city        42.518182
percent_senior       9.781818
physicians        1828.333333
hospital_beds     6345.868687
graduates           54.463636
work_force         449.366667
income            6762.505051
region               2.494949
crime_rate          55.643030
dtype: float64

 
 land_area         1951.00
percent_city        39.50
percent_senior       9.70
physicians         774.00
hospital_beds     3472.00
graduates           54.00
work_force         257.20
income            3510.00
region               3.00
crime_rate          56.06
dtype: float64


In [95]:
dataset.income.unique() #provides all the unique value of the feature.

array([72100, 54542, 33216, 32906, 26573, 25663, 18350, 18221, 15826,
       14542, 15953, 14684, 12107, 12591, 10918, 10104,  7989,  9037,
        7399,  9106,  7766,  7736,  7038,  6658,  6966,  5909,  5705,
        4941,  5094,  5142,  4924,  4798,  4600,  5181,  4127,  4102,
        3860,  4177,  3667,  4144,  4035,  3777,  3489,  4352,  3725,
        3553,  3915,  2962,  3627,  3724,  2991,  3283,  2598,  3007,
        2747,  3158,  2853,  2012,  2885,  2689,  2308,  2651,  1992,
        2201,  2662,  2439,  2264,  2257,  2088,  1996,  2178,  2396,
        1862,  1939,  2098,  1782,  2010,  1692,  1641,  1724,  1787,
        1639,  1853,  1776,  1980,  1354,  1688,  1654,  3510,  3982,
        1412,  1790,  1458,  1386,  1452,   769,  1337,  1589,  1148],
      dtype=int64)

In [96]:
dataset.crime_rate.value_counts() #This will give you counts of all unique value in the dataframe or dataset feature.

70.66    2
62.63    1
64.91    1
58.12    1
53.98    1
        ..
63.20    1
65.05    1
56.55    1
53.68    1
72.25    1
Name: crime_rate, Length: 98, dtype: int64

In [97]:
#sorting, an important feature to find a feature with highest value to owest value

dataset.sort_values(by = 'crime_rate').head(10) # here the dataframe is displayed by crime rate having lowest to highest

land_area  percent_city  percent_senior  physicians  hospital_beds  \
70        946          16.4            11.1         366           1455   
38       1951          28.4            14.5         696           4843   
76        862          26.3            13.4         423           1929   
72       2658          39.0            12.2         365           5430   
8        3049          19.5            12.1        4005          21149   
39       1490          33.1            11.9         827           3818   
97        813          13.4            10.9         371           4355   
95       1543          39.6             8.1         159            481   
75       2071          19.9            11.3         470           2531   
86        813          46.0             9.8         293           1693   

    graduates  work_force  income  region  crime_rate  
70       43.9       163.8    2178       1       23.32  
38       47.9       271.5    3667       1       23.64  
76       43.3       145.5    2010       1       25.49  
72       49.9       136.9    1862       1       28.52  
8        53.4       967.5   15826       1       30.51  
39       47.4       300.2    4144       1       30.59  
97       58.0        97.0    1589       1       36.33  
95       30.3        80.6     769       3       36.36  
75       58.9       133.1    1782       1       36.47  
86       58.4       119.9    1688       1       38.24

In [98]:
dataset.sort_values(by = 'income',ascending = False).head(10)

# here the dataframe is displayed by income by highest to lowest.

land_area  percent_city  percent_senior  physicians  hospital_beds  \
0        1384          78.1            12.3       25627          69678   
1        3719          43.9             9.4       13326          43292   
2        3553          37.4            10.7        9724          33731   
3        3916          29.9             8.8        6402          24167   
4        2480          31.5            10.5        8502          16751   
5        2815          23.1             6.7        7340          16941   
6        8360          46.3             8.2        4047          14347   
7        6794          60.1             6.3        4562          14333   
10       1008          16.6            10.3        4006          16704   
8        3049          19.5            12.1        4005          21149   

    graduates  work_force  income  region  crime_rate  
0        50.1      4083.9   72100       1       75.55  
1        53.9      3305.9   54542       2       56.03  
2        50.6      2066.3   33216       1       41.32  
3        52.2      1966.7   32906       2       67.38  
4        66.1      1514.5   26573       4       80.19  
5        68.3      1541.9   25663       3       58.48  
6        53.6      1321.2   18350       3       72.25  
7        51.7      1272.7   18221       3       64.88  
10       55.9       935.5   15953       1       54.16  
8        53.4       967.5   15826       1       30.51

In [99]:
#renaming the features

dataset.rename(columns ={'income' : 'income_individual', 'graduates' : 'graduates_individual'}, inplace = True)

dataset.head(10)

land_area  percent_city  percent_senior  physicians  hospital_beds  \
0       1384          78.1            12.3       25627          69678   
1       3719          43.9             9.4       13326          43292   
2       3553          37.4            10.7        9724          33731   
3       3916          29.9             8.8        6402          24167   
4       2480          31.5            10.5        8502          16751   
5       2815          23.1             6.7        7340          16941   
6       8360          46.3             8.2        4047          14347   
7       6794          60.1             6.3        4562          14333   
8       3049          19.5            12.1        4005          21149   
9       4647          31.5             9.2        3916          12815   

   graduates_individual  work_force  income_individual  region  crime_rate  
0                  50.1      4083.9              72100       1       75.55  
1                  53.9      3305.9              54542       2       56.03  
2                  50.6      2066.3              33216       1       41.32  
3                  52.2      1966.7              32906       2       67.38  
4                  66.1      1514.5              26573       4       80.19  
5                  68.3      1541.9              25663       3       58.48  
6                  53.6      1321.2              18350       3       72.25  
7                  51.7      1272.7              18221       3       64.88  
8                  53.4       967.5              15826       1       30.51  
9                  65.1      1032.2              14542       2       55.30

In [100]:
#renaming through indexing

dataset.rename(index = {0 : 'zero'}).head(10) 

land_area  percent_city  percent_senior  physicians  hospital_beds  \
zero       1384          78.1            12.3       25627          69678   
1          3719          43.9             9.4       13326          43292   
2          3553          37.4            10.7        9724          33731   
3          3916          29.9             8.8        6402          24167   
4          2480          31.5            10.5        8502          16751   
5          2815          23.1             6.7        7340          16941   
6          8360          46.3             8.2        4047          14347   
7          6794          60.1             6.3        4562          14333   
8          3049          19.5            12.1        4005          21149   
9          4647          31.5             9.2        3916          12815   

      graduates_individual  work_force  income_individual  region  crime_rate  
zero                  50.1      4083.9              72100       1       75.55  
1                     53.9      3305.9              54542       2       56.03  
2                     50.6      2066.3              33216       1       41.32  
3                     52.2      1966.7              32906       2       67.38  
4                     66.1      1514.5              26573       4       80.19  
5                     68.3      1541.9              25663       3       58.48  
6                     53.6      1321.2              18350       3       72.25  
7                     51.7      1272.7              18221       3       64.88  
8                     53.4       967.5              15826       1       30.51  
9                     65.1      1032.2              14542       2       55.30

In [101]:
# Missing values

dataset.isna() #If ever there was a null value, it will be shown as True or Null value is present

land_area  percent_city  percent_senior  physicians  hospital_beds  \
0       False         False           False       False          False   
1       False         False           False       False          False   
2       False         False           False       False          False   
3       False         False           False       False          False   
4       False         False           False       False          False   
..        ...           ...             ...         ...            ...   
94      False         False           False       False          False   
95      False         False           False       False          False   
96      False         False           False       False          False   
97      False         False           False       False          False   
98      False         False           False       False          False   

    graduates_individual  work_force  income_individual  region  crime_rate  
0                  False       False              False   False       False  
1                  False       False              False   False       False  
2                  False       False              False   False       False  
3                  False       False              False   False       False  
4                  False       False              False   False       False  
..                   ...         ...                ...     ...         ...  
94                 False       False              False   False       False  
95                 False       False              False   False       False  
96                 False       False              False   False       False  
97                 False       False              False   False       False  
98                 False       False              False   False       False  

[99 rows x 10 columns]

In [102]:
dataset.isnull() #If ever there was a null value, it will be shown as True or Null value is present

land_area  percent_city  percent_senior  physicians  hospital_beds  \
0       False         False           False       False          False   
1       False         False           False       False          False   
2       False         False           False       False          False   
3       False         False           False       False          False   
4       False         False           False       False          False   
..        ...           ...             ...         ...            ...   
94      False         False           False       False          False   
95      False         False           False       False          False   
96      False         False           False       False          False   
97      False         False           False       False          False   
98      False         False           False       False          False   

    graduates_individual  work_force  income_individual  region  crime_rate  
0                  False       False              False   False       False  
1                  False       False              False   False       False  
2                  False       False              False   False       False  
3                  False       False              False   False       False  
4                  False       False              False   False       False  
..                   ...         ...                ...     ...         ...  
94                 False       False              False   False       False  
95                 False       False              False   False       False  
96                 False       False              False   False       False  
97                 False       False              False   False       False  
98                 False       False              False   False       False  

[99 rows x 10 columns]

In [103]:
dataset.isnull().sum() #Summation of all the null values present in the dataframe.

land_area               0
percent_city            0
percent_senior          0
physicians              0
hospital_beds           0
graduates_individual    0
work_force              0
income_individual       0
region                  0
crime_rate              0
dtype: int64

In [104]:
dataset.land_area.fillna('XYZ') #If you come across a null value, you can fillit with anything, except NaN

0     1384
1     3719
2     3553
3     3916
4     2480
      ... 
94    1511
95    1543
96    1011
97     813
98     654
Name: land_area, Length: 99, dtype: int64

In [106]:
dataset.land_area.value_counts()

1758     2
813      2
2815     1
5677     1
27293    1
        ..
1011     1
2710     1
2013     1
2528     1
3072     1
Name: land_area, Length: 97, dtype: int64

In [107]:
# If you come across a null value in the numerical feature, 
#    you can either perform mean function or median function to replace that null value.

dataset['percent_city'].fillna(dataset['percent_city'].mean(),inplace = True)

dataset

land_area  percent_city  percent_senior  physicians  hospital_beds  \
0        1384          78.1            12.3       25627          69678   
1        3719          43.9             9.4       13326          43292   
2        3553          37.4            10.7        9724          33731   
3        3916          29.9             8.8        6402          24167   
4        2480          31.5            10.5        8502          16751   
..        ...           ...             ...         ...            ...   
94       1511          38.7            10.7         348           1093   
95       1543          39.6             8.1         159            481   
96       1011          37.8            10.5         264            964   
97        813          13.4            10.9         371           4355   
98        654          28.8             3.9         140           1296   

    graduates_individual  work_force  income_individual  region  crime_rate  
0                   50.1      4083.9              72100       1       75.55  
1                   53.9      3305.9              54542       2       56.03  
2                   50.6      2066.3              33216       1       41.32  
3                   52.2      1966.7              32906       2       67.38  
4                   66.1      1514.5              26573       4       80.19  
..                   ...         ...                ...     ...         ...  
94                  50.4       127.2               1452       4       70.66  
95                  30.3        80.6                769       3       36.36  
96                  70.7        93.2               1337       3       60.16  
97                  58.0        97.0               1589       1       36.33  
98                  55.1        66.9               1148       3       68.76  

[99 rows x 10 columns]

In [108]:
# If you wish to copy the existing dataframe to a new dataframe because, 
#   you want to change or check something but don't wish the whole dataframe to be altered.

data_cpy = dataset.copy()

data_cpy

land_area  percent_city  percent_senior  physicians  hospital_beds  \
0        1384          78.1            12.3       25627          69678   
1        3719          43.9             9.4       13326          43292   
2        3553          37.4            10.7        9724          33731   
3        3916          29.9             8.8        6402          24167   
4        2480          31.5            10.5        8502          16751   
..        ...           ...             ...         ...            ...   
94       1511          38.7            10.7         348           1093   
95       1543          39.6             8.1         159            481   
96       1011          37.8            10.5         264            964   
97        813          13.4            10.9         371           4355   
98        654          28.8             3.9         140           1296   

    graduates_individual  work_force  income_individual  region  crime_rate  
0                   50.1      4083.9              72100       1       75.55  
1                   53.9      3305.9              54542       2       56.03  
2                   50.6      2066.3              33216       1       41.32  
3                   52.2      1966.7              32906       2       67.38  
4                   66.1      1514.5              26573       4       80.19  
..                   ...         ...                ...     ...         ...  
94                  50.4       127.2               1452       4       70.66  
95                  30.3        80.6                769       3       36.36  
96                  70.7        93.2               1337       3       60.16  
97                  58.0        97.0               1589       1       36.33  
98                  55.1        66.9               1148       3       68.76  

[99 rows x 10 columns]